[book]
authors = ["Shigeyuki"]
language = "en"
multilingual = false
src = "src"
title = "Shige addons Wiki"


[output.html]
git-repository-url = "https://www.patreon.com/Shigeyuki"
git-repository-icon = "fa-envelope"
default-theme = "navy"
no-section-label = false
edit-url-template = "https://github.com/shigeyukey/Anki-faqs-jp/edit/src/{path}"


[output.html.print]
enable = false


[output.html.fold]
enable = true