[book]
authors = ["Shigeyuki"]
language = "en"
multilingual = false
src = "src"
title = "Shige addons Wiki"
default-theme = "navy"

[output.html]
git-repository-url = "https://www.patreon.com/Shigeyuki"
git-repository-icon = "fa-envelope"


[output.html.print]
enable = false

[output.html.fold]
enable = true